### ISSUE TITLE
Question: Difference to pgrange/bash_unit

### ISSUE THREAD

**Issue by alfredbez** [Chemaclass/bashunit#8]
Hi there, just saw this project and wondered how this related to https://github.com/pgrange/bash_unit ?

Maybe it's worth answering this question in the Readme.md?

**Comment by Chemaclass** [comment]
![Screenshot 2023-09-07 at 10 41 37](https://github.com/Chemaclass/bashunit/assets/5256287/fb1e50e6-2eeb-4fde-a5ef-a346acd6aead)

With the truth ahead, I started this **bashunit** idea out of the necessity of a [bash logic I wanted to assert](https://github.com/Chemaclass/conventional-commits/blob/main/tests/prepare-commit-msg_test.sh) with the bare minimum overhead. Also, I am pretty confident with PHPUnit and wanted to have a similar "developer testing experience" in bash. Although I am not that good at the bash, I thought this project could help me explore and learn more about the bash ecosystem while doing it, always with a focus on simplicity from the POV of a regular-non-expert-bash-dev.

After publishing this project on [X/Twitter](https://twitter.com/Chemaclass/status/1698805301779001658), I got a lot of great feedback from different people mentioning different testing frameworks. E.g., [bats](https://twitter.com/omgzen/status/1698952155925782940) or even bash_unit, as you are mentioning now.

The fact is that this is working pretty well, and there are a few things we want to do (with some friends helping me move forward with this project) with the aim of simplicity and focus on the developer experience over anything else.

Right now, bash_unit, bats, or others might have way more features than **bashunit**... but it's about time to catch up on all those basic features. Then, you can choose the one that helps you the most based on the syntax and, ultimately, dev-experience.

It's true that **bashunit** just arrived at "the market," but we will have fun building it and learning along the way. Community and test-driven, that's for sure.

**Comment by alfredbez** [comment]
Thanks for your explanation 👍

**Comment by pgrange** [comment]
Congrats on the progress—from 15 stars to 320, that's impressive!
Just a small suggestion: naming it bashunit might be a bit confusing, especially since there's already a project called bash_unit' Maybe consider tweaking the name for clarity?
Keep up the great work, though!
The more the better. Cheers.

**Comment by pgrange** [comment]
By the way, _bash unit testing enterprise edition framework for professionals!_ was totally a joke. I was just so fed up with all these so-called enterprise frameworks—which often turned out to be a huge pile of nonsense—that I figured I'd use the same over-the-top language to describe this minimalistic side project I was working on. I would never have thought people would take it seriously one day 😉

**Comment by Chemaclass** [comment]
Hi, @pgrange ! It's a pleasure to talk to you 1:1 😄 Thanks for the feedback and the congrats. Likewise! 

We don't plan to change the project name because it is already well-rooted in our community, the overall installation process, and other tools using it. I think it's OK to keep both names as they are. There is enough "market" for both, and I don't think it harms any of us in the current situation.

Your bash_unit project got over 600 stars; much respect to that 👌🏼
